name: ci

on:
  push:
  pull_request:

jobs:
  moonbit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1.22

      - name: Check
        run: moon check

      - name: Test
        run: moon test

      - name: Run example
        run: moon run cmd/main
