name: ci

on:
  push:
  pull_request:

jobs:
  moonbit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Moon env
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Format Check
        run: moon fmt --check

      - name: Info Check
        run: moon info

      - name: Check
        run: moon check --deny-warn

      - name: Test
        run: moon test

      - name: Run example
        run: moon run cmd/main
